// src/pages/index.jsx
import Head from 'next/head';
import Weather from '../components/Weather';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-8">
        <h1 className="text-3xl font-bold underline">
          Weather App
        </h1>
        <Weather />
      </main>
    </div>
  );
}
